### ISSUE TITLE
get rid of deprecation warnings in the build

### ISSUE THREAD

**Issue by axel22** [scala-blitz/scala-blitz#30]

**Comment by DarkDimius** [comment]
There are currently 2 deprecation warnings that I know of:
1) range.numElements is deprecated, can be easily fixed
2) Context is deprecated in favor of either BlackBoxContext or WhiteBoxContext. Note that neither of those exists in 2.10, but as we chose to build 2.10 with Macro Paradise this shouldn't be a problem. All macros except 'optimize' should are currently blackbox, AFAIK.

You've meant those?

**Comment by axel22** [comment]
Yep!

**Comment by axel22** [comment]
Shouldn't you be sleeping? :)
