### ISSUE TITLE
value ClassTag not found on Array init

### ISSUE THREAD

**Issue by HairyFotr** [scala-blitz/scala-blitz#34]
If I try to initialize an Array (for example with `ofDim` or `fill`), inside a block under toPar, I get this error:

```
scala> for(i <- (0 until 10).toPar) { val a = Array.fill(5)(1d) }
<console>:24: error: not found: value ClassTag
              for(i <- (0 until 10).toPar) { val a = Array.fill(5)(1d) }
                                                                  ^
```

I can workaround the issue by importing scala.reflect.ClassTag. I've only seen this issue happen for Arrays so far.

I'm using scala-blitz 1.0-M2 with scala 2.11.0-M7.

**Comment by DarkDimius** [comment]
Should be fixed in latest 1.1-SNAPSHOT for scala 2.11
